import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" h-full w-full">
        <Navigation />
        <div>{children}</div>
      </body>
    </html>
  );
}
// h-full w-full lg:basis-[calc(100%-200px)]
